/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ArcPaySchedulerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelSchedule"
      | "createSchedule"
      | "executeSchedule"
      | "schedules"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PaymentSent"
      | "ScheduleCancelled"
      | "ScheduleCreated"
      | "ScheduleExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelSchedule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createSchedule",
    values: [
      string,
      AddressLike[],
      BigNumberish[],
      string[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSchedule",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "schedules", values: [string]): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "cancelSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace PaymentSentEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    memo: string
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    memo: string
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCancelledEvent {
  export type InputTuple = [id: string, owner: AddressLike];
  export type OutputTuple = [id: string, owner: string];
  export interface OutputObject {
    id: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [
    id: string,
    owner: AddressLike,
    nextRun: BigNumberish,
    interval: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    owner: string,
    nextRun: bigint,
    interval: bigint
  ];
  export interface OutputObject {
    id: string;
    owner: string;
    nextRun: bigint;
    interval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleExecutedEvent {
  export type InputTuple = [
    id: string,
    executor: AddressLike,
    executedAt: BigNumberish,
    nextRun: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    executor: string,
    executedAt: bigint,
    nextRun: bigint
  ];
  export interface OutputObject {
    id: string;
    executor: string;
    executedAt: bigint;
    nextRun: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPayScheduler extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPayScheduler;
  waitForDeployment(): Promise<this>;

  interface: ArcPaySchedulerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelSchedule: TypedContractMethod<[id: string], [void], "nonpayable">;

  createSchedule: TypedContractMethod<
    [
      id: string,
      _to: AddressLike[],
      _amounts: BigNumberish[],
      _memos: string[],
      _nextRun: BigNumberish,
      _interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeSchedule: TypedContractMethod<[id: string], [void], "nonpayable">;

  schedules: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        owner: string;
        nextRun: bigint;
        interval: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelSchedule"
  ): TypedContractMethod<[id: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSchedule"
  ): TypedContractMethod<
    [
      id: string,
      _to: AddressLike[],
      _amounts: BigNumberish[],
      _memos: string[],
      _nextRun: BigNumberish,
      _interval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeSchedule"
  ): TypedContractMethod<[id: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "schedules"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, bigint, boolean] & {
        owner: string;
        nextRun: bigint;
        interval: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PaymentSent"
  ): TypedContractEvent<
    PaymentSentEvent.InputTuple,
    PaymentSentEvent.OutputTuple,
    PaymentSentEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCancelled"
  ): TypedContractEvent<
    ScheduleCancelledEvent.InputTuple,
    ScheduleCancelledEvent.OutputTuple,
    ScheduleCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleExecuted"
  ): TypedContractEvent<
    ScheduleExecutedEvent.InputTuple,
    ScheduleExecutedEvent.OutputTuple,
    ScheduleExecutedEvent.OutputObject
  >;

  filters: {
    "PaymentSent(address,address,uint256,string)": TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;
    PaymentSent: TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;

    "ScheduleCancelled(string,address)": TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;
    ScheduleCancelled: TypedContractEvent<
      ScheduleCancelledEvent.InputTuple,
      ScheduleCancelledEvent.OutputTuple,
      ScheduleCancelledEvent.OutputObject
    >;

    "ScheduleCreated(string,address,uint256,uint256)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;

    "ScheduleExecuted(string,address,uint256,uint256)": TypedContractEvent<
      ScheduleExecutedEvent.InputTuple,
      ScheduleExecutedEvent.OutputTuple,
      ScheduleExecutedEvent.OutputObject
    >;
    ScheduleExecuted: TypedContractEvent<
      ScheduleExecutedEvent.InputTuple,
      ScheduleExecutedEvent.OutputTuple,
      ScheduleExecutedEvent.OutputObject
    >;
  };
}
