/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BountyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounties"
      | "cancelBounty"
      | "depositBounty"
      | "getBounty"
      | "refundExpiredBounty"
      | "releasePrize"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyCreated"
      | "BountyFunded"
      | "BountyRefunded"
      | "RewardReleased"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bounties", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBounty",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "refundExpiredBounty",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePrize",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundExpiredBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: string,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    bountyId: string;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: string,
    creator: string,
    amount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    bountyId: string;
    creator: string;
    amount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyFundedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: string,
    creator: string,
    amount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    bountyId: string;
    creator: string;
    amount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyRefundedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: string, creator: string, amount: bigint];
  export interface OutputObject {
    bountyId: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReleasedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: string, winner: string, amount: bigint];
  export interface OutputObject {
    bountyId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: string, winner: string, amount: bigint];
  export interface OutputObject {
    bountyId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BountyEscrow;
  waitForDeployment(): Promise<this>;

  interface: BountyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounties: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  cancelBounty: TypedContractMethod<
    [bountyId: BytesLike],
    [void],
    "nonpayable"
  >;

  depositBounty: TypedContractMethod<
    [bountyId: BytesLike, amount: BigNumberish, deadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBounty: TypedContractMethod<
    [bountyId: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  refundExpiredBounty: TypedContractMethod<
    [bountyId: BytesLike],
    [void],
    "nonpayable"
  >;

  releasePrize: TypedContractMethod<
    [bountyId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositBounty"
  ): TypedContractMethod<
    [bountyId: BytesLike, amount: BigNumberish, deadline: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BytesLike],
    [
      [string, bigint, bigint, bigint, string] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refundExpiredBounty"
  ): TypedContractMethod<[bountyId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePrize"
  ): TypedContractMethod<
    [bountyId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyFunded"
  ): TypedContractEvent<
    BountyFundedEvent.InputTuple,
    BountyFundedEvent.OutputTuple,
    BountyFundedEvent.OutputObject
  >;
  getEvent(
    key: "BountyRefunded"
  ): TypedContractEvent<
    BountyRefundedEvent.InputTuple,
    BountyRefundedEvent.OutputTuple,
    BountyRefundedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReleased"
  ): TypedContractEvent<
    RewardReleasedEvent.InputTuple,
    RewardReleasedEvent.OutputTuple,
    RewardReleasedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(bytes32,address,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(bytes32,address,uint256,uint256)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "BountyFunded(bytes32,address,uint256,uint256)": TypedContractEvent<
      BountyFundedEvent.InputTuple,
      BountyFundedEvent.OutputTuple,
      BountyFundedEvent.OutputObject
    >;
    BountyFunded: TypedContractEvent<
      BountyFundedEvent.InputTuple,
      BountyFundedEvent.OutputTuple,
      BountyFundedEvent.OutputObject
    >;

    "BountyRefunded(bytes32,address,uint256)": TypedContractEvent<
      BountyRefundedEvent.InputTuple,
      BountyRefundedEvent.OutputTuple,
      BountyRefundedEvent.OutputObject
    >;
    BountyRefunded: TypedContractEvent<
      BountyRefundedEvent.InputTuple,
      BountyRefundedEvent.OutputTuple,
      BountyRefundedEvent.OutputObject
    >;

    "RewardReleased(bytes32,address,uint256)": TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;
    RewardReleased: TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;

    "WinnerSelected(bytes32,address,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
