/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BountyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounties"
      | "depositBounty"
      | "getBounty"
      | "releasePrize"
      | "usdcToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BountyFunded" | "PrizeReleased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "bounties", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "depositBounty",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePrize",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
}

export namespace BountyFundedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: string, creator: string, amount: bigint];
  export interface OutputObject {
    bountyId: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeReleasedEvent {
  export type InputTuple = [
    bountyId: BytesLike,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: string, winner: string, amount: bigint];
  export interface OutputObject {
    bountyId: string;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BountyEscrow;
  waitForDeployment(): Promise<this>;

  interface: BountyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounties: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        creator: string;
        amount: bigint;
        funded: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;

  depositBounty: TypedContractMethod<
    [bountyId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBounty: TypedContractMethod<
    [bountyId: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        creator: string;
        amount: bigint;
        funded: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;

  releasePrize: TypedContractMethod<
    [bountyId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        creator: string;
        amount: bigint;
        funded: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositBounty"
  ): TypedContractMethod<
    [bountyId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BytesLike],
    [
      [string, bigint, boolean, boolean] & {
        creator: string;
        amount: bigint;
        funded: boolean;
        paid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "releasePrize"
  ): TypedContractMethod<
    [bountyId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BountyFunded"
  ): TypedContractEvent<
    BountyFundedEvent.InputTuple,
    BountyFundedEvent.OutputTuple,
    BountyFundedEvent.OutputObject
  >;
  getEvent(
    key: "PrizeReleased"
  ): TypedContractEvent<
    PrizeReleasedEvent.InputTuple,
    PrizeReleasedEvent.OutputTuple,
    PrizeReleasedEvent.OutputObject
  >;

  filters: {
    "BountyFunded(bytes32,address,uint256)": TypedContractEvent<
      BountyFundedEvent.InputTuple,
      BountyFundedEvent.OutputTuple,
      BountyFundedEvent.OutputObject
    >;
    BountyFunded: TypedContractEvent<
      BountyFundedEvent.InputTuple,
      BountyFundedEvent.OutputTuple,
      BountyFundedEvent.OutputObject
    >;

    "PrizeReleased(bytes32,address,uint256)": TypedContractEvent<
      PrizeReleasedEvent.InputTuple,
      PrizeReleasedEvent.OutputTuple,
      PrizeReleasedEvent.OutputObject
    >;
    PrizeReleased: TypedContractEvent<
      PrizeReleasedEvent.InputTuple,
      PrizeReleasedEvent.OutputTuple,
      PrizeReleasedEvent.OutputObject
    >;
  };
}
